# Generated by Django 3.0.7 on 2020-06-23 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=30)),
                ('clubeA', models.CharField(max_length=30)),
                ('clubeB', models.CharField(max_length=30)),
                ('estadio', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Torcedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=70)),
                ('idade', models.PositiveSmallIntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.Ingresso')),
                ('torcedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.Torcedor')),
            ],
        ),
    ]
