# Generated by Django 3.0.7 on 2020-06-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='preco',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='torcedor',
            name='idade',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
