# Generated by Django 2.2.6 on 2020-07-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20200623_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='status',
            field=models.CharField(default='Disponível', max_length=40),
        ),
    ]
